version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  unit-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Unit Test
          command: ./gradlew testDebugUnitTest :app:testSandDebugUnitTest
          no_output_timeout: 20m
      - android/save-gradle-cache
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

workflows:
  unit-tests:
    jobs:
      - unit-test
