version: 2.1

## Docker container setup

config_android: &config_android
  docker:
    - image: circleci/android:api-30
  working_directory: ~/code
  environment:
    TERM: dumb

## Caching information

restore_cache: &restore_cache
  restore_cache:
    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

save_cache: &save_cache
  save_cache:
    paths:
      - ~/.gradle/caches
      - ~/.gradle/wrapper
    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

## Setup command to run any extra commands on the device

setup_env: &setup_env
  steps:
    - <<: *restore_cache
    - run:
        name: Update dependencies
        command: ./gradlew dependencies
    - <<: *save_cache
    - run:
        name: Fixing gradlew permissions
        command: sudo chmod +x ./gradlew


## Jobs

jobs:
  test:
    <<: *config_android
    steps:
      - checkout
      - <<: *setup_env
      - run:
          name: Running unit tests - app
          command: ./gradlew :app:testLiveReleaseUnitTest
      - run:
          name: Running unit tests - repo
          command: ./gradlew :repo:test

  build_deploy:
    <<: *config_android
    steps:
      - checkout
      - <<: *setup_env
      - run:
          name: Assemble release build
          command: ./gradlew publishRelease

## Workflows

workflows:
  version: 2

  run_tests:
    jobs:
      - test:
          filters:
            branches:
              only: master

  run_build_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              only: master
      - build_deploy:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              only: master