name: Dependency Report
'on':
  workflow_dispatch:

jobs:
  dependency_report:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Caching gradle
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/*.toml*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Dependency report
      - name: Generating Dependency Report
        run: ./gradlew dependencyUpdates

      # Print Dependency summary
      - name: Dumping summary in job
        run: cat reports/android-flashback-dependencies-result.html >> $GITHUB_STEP_SUMMARY
