name: Version bumping
'on':
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version name (ie. 1.0.0)'
        required: true
        default: '0.0.0'
      version_code:
        description: 'Version code (ie. 1)'
        required: true
        default: '0'
      is_major:
        description: 'Is this a major release'
        required: true
        default: 'false'
      title:
        description: 'Title for release'
        required: true
        default: ''
      notes1:
        description: 'Notes line 1'
        required: true
        default: 'New release!'
      notes2:
        description: 'Notes line 2'
        required: true
        default: ''
      notes3:
        description: 'Notes line 3'
        required: true
        default: ''
      notes4:
        description: 'Notes line 4'
        required: true
        default: ''
      notes5:
        description: 'Notes line 4'
        required: true
        default: ''
jobs:
  add_release:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Create JSON
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "release-notes/${{ github.event.inputs.version_name }}.json"
          json: """{
  'versionName': '${{ github.event.inputs.version_name }}',
  'versionCode': '${{ github.event.inputs.version_code }}',
  'isMajor': '${{ github.event.inputs.is_major }}',
  'title': ${{ github.event.inputs.title }}',
  'notes': [
    '${{ github.event.inputs.notes1 }}'
  ]
}
"""

      # Perform git checkout updates
      - name: Commit changes
        run: |
          echo "pr_branch=release/${{ github.event.inputs.version_code }}"
          echo "${{ env.pr_branch }}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b ${{ env.pr_branch }}
          git status
          git add release-notes/
          git commit -am "Bumped version to ${{ github.event.inputs.version_name }} (${{ github.event.inputs.version_code }})"

      # Push branch to github
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.pr_branch }}

      # Raise PR
      - name: Initialize Pull Request
        uses: gha-utilities/init-pull-request@v0.3.1
        with:
          verbose: true
          pull_request_token: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ env.pr_branch }}
          base: main
          title: 'Release: ${{ github.event.inputs.version_name }} (${{ github.event.inputs.version_code }})'
          body: >
            Perhaps a multi-line description
            about latest features and such.