name: Version bumping
'on':
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version name (ie. 1.0.0)'
        required: true
        default: '0.0.0'
      versionCode:
        description: 'Version code (ie. 1)'
        required: true
        default: '0'
      isMajor:
        description: 'Is this a major release'
        required: true
        default: 'false'
      title:
        description: 'Title for release'
        required: false
        default: ''
      notes:
        description: 'Notes line'
        required: true
        default: "'New release!','Also this happened'"

jobs:
  addrelease:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Variables
      - name: Variables
        run: |
          echo "pr_branch=release/${{ github.event.inputs.versionCode }}" >> $GITHUB_ENV
          echo "file=release-notes/${{ github.event.inputs.versionName }}.json" >> $GITHUB_ENV

      # Create JSON
      - name: Create json
        run: echo $JSON >> ${{ env.file }}
        env:
          JSON: |
            {
              'versionName': '${{ github.event.inputs.versionName }}',
              'versionCode': '${{ github.event.inputs.versionCode }}',
              'isMajor': '${{ github.event.inputs.isMajor }}',
              'title': '${{ github.event.inputs.title }}',
              'notes': [
                ${{ github.event.inputs.notes }}
              ]
            }

      # Perform git checkout updates
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b ${{ env.pr_branch }}
          git status
          git add release-notes/
          git commit -am "Bumped version to ${{ github.event.inputs.versionName }} (${{ github.event.inputs.versionCode }})"

       # Push branch to github
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.pr_branch }}

      # Raise PR
      - name: Initialize Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ env.pr_branch }}
          base: main
          labels: Release
          title: 'Release ${{ github.event.inputs.versionName }} (${{ github.event.inputs.versionCode }})'
          assignees: thementalgoose
          draft: false